# Builds and runs the application as default.
all: build runs

# Builds the application.
build:
	@g++ <INPUT-FILES> -o app -Wall -Werror -std=c++17

# Runs the application.
run:
	@./app

# Cleans the application.
clean:
	@rm -f app