# Builds and runs the application as default.
all: build run

# Builds the application.
build:
	@gcc main.c vector.c -o main -Wall -Werror
	
# Runs the application.
run:
	@./main

# Cleans the application.
clean:
	@rm -f main