# Builds and runs the application as default.
all: build run

# Builds the application.
build:
	@g++ main.cpp -o main

# Runs the application.
run:
	@./main

# Removes compiled files.
clean:
	@rm -f main