# Builds and runs the application as default.
all: build runs

# Build the application.
build:
	@g++ main.cpp node.cpp -o main -Wall -Werror

# Runs the application.
runs:
	@./main

# Removes the executable.
clean:
	@rm -f main