# Builds and runs the application as default.
default: build run 

# Builds the application.
build:
	@g++ main.cpp -o main -Wall -Werror

# Runs the application.
run:
	@./main

# Removes compiled files.
clean:
	@rm -f main